# Makefile for Lab03-Blinky, ELEC424 Fall 2014
# Authors: Jie Liao, Abeer Javed, Steven Arroyo. Rice University 
# Derived from the crazyflie-firmware Makefile

# Path Definitions
STM_LIB = ~/Documents/Programming/ELEC\ 424/crazyflie-firmware
CONFIG = /config
PERIPH_DRIVERS = /lib/STM32F10x_StdPeriph_Driver/inc
CM3 = /lib/CMSIS/Core/CM3
STARTUP = /startup/gcc

# In Folder Definitions
LINKER_SCRIPT = linker_script

# Compiler 
CC = arm-none-eabi-gcc

# Particular processor
PROCESSOR = -mcpu=cortex-m3 -mthumb

# Directories of used header files
INCLUDE = -I$(STM_LIB)$(PERIPH_DRIVERS) -I$(STM_LIB)$(CM3)

# STM chip specific flags
STFLAGS = -DSTM32F10X_MD -include $(STM_LIB)$(CONFIG)/stm32f10x_conf.h

# Define the compiler flags
CFLAGS = -O0 -g3 $(PROCESSOR) $(INCLUDE) $(STFLAGS) -Wl,--gc-sections -T $(LINKER_SCRIPT)/stm32_flash.ld

# Build all relevant files and create .elf
all:
	@$(CC) $(CFLAGS) $(STM_LIB)$(CM3)$(STARTUP)/startup_stm32f10x_md.s ??

# Program .elf into Crazyflie flash memory via the busblaster
flash:
	@openocd -d0 -f interface/busblaster.cfg -f target/stm32f1x.cfg -c init -c targets -c "reset halt" -c "flash write_image erase blinky_fast.elf" -c "verify_image blinky_fast.elf" -c "reset run" -c shutdown

 
# Runs OpenOCD, opens GDB terminal, and establishes connection with Crazyflie
debug:
	@ openocd -g -d0 -f interface/busblaster.cfg -f target/stm32f1x.cfg -c init -c targets -c "reset halt" & 
	arm-none-eabi-gdb -e "blinky_fast.elf" -x target
	killall openocd


# Remove all files generated by target 'all'
clean:
	rm 
